Loading Product Skeleton
Lambda-School-Labs/merchant-marketplace-a-fe pull request #23
Opened 2021-02-26 03:52 UTC by edelveiss

# Description
Loading Product Skeleton provides a placeholder while waiting for product content to load.
## Type of change
- [ ] New feature (non-breaking change which adds functionality)
## Change Status
- [ ] Complete, tested, ready to review and merge
# Checklist
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] There are no merge conflicts

2021-02-26 04:06 UTC, lgv-0 requested changes
Please fix the test coverage warnings 👍

2021-02-26 04:40 UTC, aaronmatson1 approved these changes
Looks good! excited to see how this is implemented

2021-02-26 04:41 UTC, lgv-0 approved these changes

2021-02-26 04:41 UTC, merged

2021-02-28 05:38 UTC, edelveiss commented
![](https://github.trello.services/images/mini-trello-icon.png) [Loading Product Skeleton](https://trello.com/c/usCAaLyu/67-loading-product-skeleton)